# Docker Compose for SmartCondominium
# Servicios: backend, frontend, base de datos PostgreSQL
version: '3.8'

services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: smartcondo
      POSTGRES_USER: smartuser
      POSTGRES_PASSWORD: smartpass
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    restart: always
    environment:
      DB_NAME: smartcondo
      DB_USER: smartuser
      DB_PASSWORD: smartpass
      DB_HOST: db
      DB_PORT: 5432
    depends_on:
      - db
    ports:
      - "8000:8000"

  frontend:
    build: ./frontend
    restart: always
    environment:
      - HOST=0.0.0.0
      - REACT_APP_API_URL=http://localhost:8000/api
    ports:
      - "3000:3000"
    depends_on:
      - backend

volumes:
  postgres_data:
